### ISSUE TITLE
Add matchdep for grunt package loading

### ISSUE THREAD

**Issue by tomfuertes** [asbjornenge/generator-microlib#3]
I'll PR this soon! Just leaving a "todo" reminder/note :)

source: http://chrisawren.com/posts/Advanced-Grunt-tooling#loading-all-grunt-tasks-automatically

``` javascript
/* 
$ npm install --save-dev matchdep 
*/

// Then add this line to your Gruntfile which will run 
// grunt.loadNpmTasks on each grunt plugin found 
// in your package.json:

require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

// Now you will never have to manually 
// add and remove grunt.loadNpmTasks :).
```

**Comment by asbjornenge** [comment]
Already in, thanks! Been hacking this today ;-) You can check out the toolchoice branch for all the new stuff. All I'm missing is some optional travis configuration, then I'm all set for a new release.
